server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://47.107.139.169:3306/test?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456

# mybatis 相关注解
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.aibaiyang.idemo.mapper : debug
