server:
  port: 8089

spring:
  datasource:
#    url: jdbc:mysql://47.107.139.169/imooc?characterEncoding=UTF8&useSSL=false
    url: jdbc:mysql://127.0.0.1/imooc?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update