server:
  port: 8089

spring:
  datasource:
#    url: jdbc:mysql://47.107.139.169/imooc?characterEncoding=UTF8&useSSL=false
    url: jdbc:mysql://127.0.0.1/imooc?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          #rocketmq地址
          name-server: 47.107.139.169:9876
      #Binding: 包括 Input Binding 和 Output Binding。
      #Binding 在消息中间件与应用程序提供的 Provider 和 Consumer 之间提供了一个桥梁，
      #实现了开发者只需使用应用程序的 Provider 或 Consumer 生产或消费数据即可，屏蔽了开发者与底层消息中间件的接触。
      bindings:
        #自定义的名称
        output1:
          destination: demo_quick_topic   # topic(一级分类)
          content-type: application/json

#  cloud:
#    stream:
#      rocketmq:
#        binder:
#          name-server: 47.107.139.169:9876
#
#      bindings:
#        output2:
#          destination: test-topic
#          content-type: application/json
#
#         input:
#           destination: test-topic
#           content-type: application/json
#           group: test-group

