server:
  port: 8088

spring:
  datasource:
#    url: jdbc:mysql://47.107.139.169/imooc?characterEncoding=UTF8&useSSL=false
    url: jdbc:mysql://127.0.0.1/imooc?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# redis 相关配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

